language: android
sudo: false

jdk:
 - oraclejdk7
 - oraclejdk8

before_install:
 - chmod +x gradlew

android:
  components:
    # We are using the latest revision of Android SDK Tools.
    - platform-tools
    - tools
    # The BuildTools version we are using for our project.
    - build-tools-21.1.2
    # System Image we use to run emulator(s) during tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

    # Additional components.
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
     - 'android-sdk-license-.+'

# Emulator Management: Create, Start and Wait.
before_script:
    # Inspecting running services.
    - ps auxww
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

notifications:
  email: false