language: java
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
  global:
    - secure: HL+OKBCpGbFB3h/0p63b5zZokMedeHfDv8gbi6HIHfoKyfxsLYZvoksEGnaeUXxjBbfJ0FGgFWh98+WoxT7rZ86TLSHK7QTQeZlvBeNVrIfgC3d4kHP+XLyg50wYOe/9fRSk9Hfp6AGHRwqq2+7yY+t0Ra2oKip56cB51rsnEWU=
    - secure: RbXqRIUZgZABfN2aMHJO5cBaMTMFR42m7kh7Wibz8kdeL792MoIjIZRvTeYYKlW+dSU+FDj2dceJEGtbSEFxa6OLNCigGetN9F8aWB6ohTNK1DB79x0OykuywQeSSBT9MZebu8H63/hjUu8M7pzKaQHS8JqdaBg03jX4G1xjCp4=

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Gradle
  - wget http://services.gradle.org/distributions/gradle-1.10-bin.zip
  - unzip gradle-1.10-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.10
  - export PATH=$GRADLE_HOME/bin:$PATH

  # install android build tools
  - wget https://dl-ssl.google.com/android/repository/build-tools_r19.0.1-linux.zip
  - unzip build-tools_r19.0.1-linux.zip -d $ANDROID_HOME
  - mkdir -p $ANDROID_HOME/build-tools/
  - mv $ANDROID_HOME/android-4.4.2 $ANDROID_HOME/build-tools/19.0.1

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Note that sysimg-18 downloads the ARM, x86 and MIPS images (we should optimize this).
  # Other relevant API's
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-18 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-19 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter sysimg-19 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - chmod +x ci/wait_for_emulator.sh
  - ci/wait_for_emulator.sh
  - adb shell input keyevent 82 &

script:
  - TERM=dumb gradle connectedInstrumentTest
